version: '3'
services:

## Uncomment this and change application.properties to run the application with docker.
  #  book_library:
  #    build:
  #      dockerfile: Dockerfile
  #      context: .
  #    depends_on:
  #      - postgres
  #    environment:
  #      - DB_USER=book_library
  #      - DB_PASS=book_library
  #      - DB_HOST=postgres
  #      - DB_NAME=book_library
  #      - DB_PORT=5432
  #    ports:
  #      - "8080:8080"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=book_library
      - POSTGRES_USER=book_library
      - POSTGRES_DB=book_library
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
